name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '16' # Use OpenJDK 16 for initial setup

    - name: Install Corretto 17
      run: |
        wget https://corretto.aws/downloads/latest/amazon-corretto-17-x64-linux-jdk.tar.gz
        tar -xzf amazon-corretto-17-x64-linux-jdk.tar.gz
        export JAVA_HOME=$(pwd)/amazon-corretto-17.x.x.x-xxx
        export PATH=$JAVA_HOME/bin:$PATH

    - name: Build and Test
      run: |
        ./mvnw clean install

    - name: Notify on failure
      if: ${{ failure() }}
      run: |
        echo "Tests failed! Please check the build."
