name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        node-version: '16'  

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: 'corretto-$JAVA_VERSION'
        node-version: '16'  

    - name: Build and Test
      run: |
        ./mvnw clean install

    - name: Notify on failure
      if: ${{ failure() }}
      run: |
        echo "Tests failed! Please check the build."
